# Generated by Django 6.0.7 on 2026-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link źródłowy'),
        ),
    ]
