# Generated by Django 6.0.7 on 2026-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Link źródłowy'),
        ),
    ]
