# Generated by Django 6.0.7 on 2026-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji'),
        ),
    ]
