# Generated by Django 6.0.7 on 2026-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='trust_level',
            field=models.CharField(choices=[('TRUSTED', 'Zaufane'), ('NORMAL', 'Standardowe'), ('BLOCKED', 'Zablokowane')], default='NORMAL', max_length=20, verbose_name='Poziom zaufania'),
        ),
    ]
